"""Seed data for LifeOS - exercises and programs."""
from typing import List, Dict, Any


# Mapping from our exercise names → yuhonas/free-exercise-db IDs.
# Image is served from raw.githubusercontent.com — see _img() below.
EXERCISE_IMAGE_SLUGS: Dict[str, str] = {
    # CHEST
    "Barbell Bench Press": "Barbell_Bench_Press_-_Medium_Grip",
    "Incline Dumbbell Press": "Incline_Dumbbell_Press",
    "Dumbbell Bench Press": "Dumbbell_Bench_Press",
    "Dumbbell Flyes": "Dumbbell_Flyes",
    "Cable Crossover": "Cable_Crossover",
    "Push Up": "Pushups",
    "Dips": "Dips_-_Chest_Version",
    "Machine Chest Press": "Cable_Chest_Press",
    # BACK
    "Pull Up": "Pullups",
    "Lat Pulldown": "Wide-Grip_Lat_Pulldown",
    "Barbell Row": "Bent_Over_Barbell_Row",
    "Dumbbell Row": "Bent_Over_Two-Dumbbell_Row",
    "T-Bar Row": "Lying_T-Bar_Row",
    "Seated Cable Row": "Seated_Cable_Rows",
    "Deadlift": "Barbell_Deadlift",
    "Face Pull": "Face_Pull",
    # SHOULDERS
    "Overhead Press": "Standing_Military_Press",
    "Dumbbell Shoulder Press": "Dumbbell_Shoulder_Press",
    "Lateral Raise": "Side_Lateral_Raise",
    "Front Raise": "Front_Dumbbell_Raise",
    "Rear Delt Fly": "Cable_Rear_Delt_Fly",
    "Arnold Press": "Arnold_Dumbbell_Press",
    "Upright Row": "Upright_Cable_Row",
    # BICEPS
    "Barbell Curl": "Barbell_Curl",
    "Dumbbell Curl": "Dumbbell_Bicep_Curl",
    "Hammer Curl": "Hammer_Curls",
    "Preacher Curl": "Preacher_Curl",
    "Concentration Curl": "Concentration_Curls",
    "Cable Curl": "High_Cable_Curls",
    # TRICEPS
    "Tricep Pushdown": "Triceps_Pushdown",
    "Skull Crusher": "EZ-Bar_Skullcrusher",
    "Overhead Tricep Extension": "Cable_Rope_Overhead_Triceps_Extension",
    "Close Grip Bench Press": "Close-Grip_Barbell_Bench_Press",
    "Tricep Dip": "Dips_-_Triceps_Version",
    "Tricep Kickback": "Tricep_Dumbbell_Kickback",
    # QUADS
    "Back Squat": "Barbell_Squat",
    "Front Squat": "Front_Barbell_Squat",
    "Leg Press": "Leg_Press",
    "Leg Extension": "Leg_Extensions",
    "Walking Lunges": "Barbell_Walking_Lunge",
    "Bulgarian Split Squat": "Split_Squats",
    "Goblet Squat": "Goblet_Squat",
    # HAMSTRINGS
    "Romanian Deadlift": "Romanian_Deadlift",
    "Lying Leg Curl": "Lying_Leg_Curls",
    "Stiff Leg Deadlift": "Stiff-Legged_Dumbbell_Deadlift",
    "Glute Ham Raise": "Glute_Ham_Raise",
    # GLUTES
    "Barbell Hip Thrust": "Barbell_Hip_Thrust",
    "Glute Bridge": "Barbell_Glute_Bridge",
    "Cable Glute Kickback": "Glute_Kickback",
    "Sumo Deadlift": "Sumo_Deadlift",
    # CALVES
    "Standing Calf Raise": "Standing_Calf_Raises",
    "Seated Calf Raise": "Seated_Calf_Raise",
    "Donkey Calf Raise": "Donkey_Calf_Raises",
    # CORE
    "Plank": "Plank",
    "Crunches": "Crunches",
    "Russian Twist": "Russian_Twist",
    "Hanging Leg Raise": "Hanging_Leg_Raise",
    "Cable Crunch": "Cable_Crunch",
    "Ab Wheel Rollout": "Ab_Roller",
    "Side Plank": "Push_Up_to_Side_Plank",
    # CARDIO
    "Treadmill Run": "Running_Treadmill",
    "Stationary Bike": "Air_Bike",
    "Rowing Machine": "Rowing_Stationary",
    "Jump Rope": "Rope_Jumping",
    "Burpees": "Pushups",  # fallback — no burpee entry exists
    "Mountain Climbers": "Mountain_Climbers",
    # --- expanded library ---
    "Incline Barbell Bench Press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
    "Decline Barbell Bench Press": "Decline_Barbell_Bench_Press",
    "Pec Deck Fly": "Butterfly",
    "Incline Cable Fly": "Incline_Cable_Flye",
    "Decline Push Up": "Decline_Push-Up",
    "Smith Machine Bench Press": "Smith_Machine_Bench_Press",
    "Chin Up": "Chin-Up",
    "Straight Arm Pulldown": "Straight-Arm_Pulldown",
    "Close Grip Lat Pulldown": "Close-Grip_Front_Lat_Pulldown",
    "Chest Supported Row": "Smith_Machine_Bent_Over_Row",
    "Machine Row": "Leverage_High_Row",
    "Rack Pull": "Rack_Pulls",
    "Pendlay Row": "Bent_Over_Barbell_Row",
    "Inverted Row": "Inverted_Row",
    "Back Extension": "Hyperextensions_Back_Extensions",
    "Good Morning": "Good_Morning",
    "Superman": "Superman",
    "Barbell Shrug": "Barbell_Shrug",
    "Dumbbell Shrug": "Dumbbell_Shrug",
    "Cable Shrug": "Cable_Shrugs",
    "Machine Shoulder Press": "Machine_Shoulder_Military_Press",
    "Cable Lateral Raise": "Cable_Seated_Lateral_Raise",
    "Reverse Pec Deck": "Reverse_Machine_Flyes",
    "Push Press": "Push_Press",
    "Seated Barbell Press": "Seated_Barbell_Military_Press",
    "EZ Bar Curl": "EZ-Bar_Curl",
    "Incline Dumbbell Curl": "Incline_Dumbbell_Curl",
    "Spider Curl": "Spider_Curl",
    "Machine Bicep Curl": "Machine_Bicep_Curl",
    "Diamond Push Up": "Push-Ups_-_Close_Triceps_Position",
    "Cable Rope Pushdown": "Triceps_Pushdown_-_Rope_Attachment",
    "Machine Tricep Extension": "Machine_Triceps_Extension",
    "Bench Dip": "Bench_Dips",
    "Wrist Curl": "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench",
    "Reverse Wrist Curl": "Palms-Down_Wrist_Curl_Over_A_Bench",
    "Reverse Barbell Curl": "Reverse_Barbell_Curl",
    "Farmers Walk": "Farmers_Walk",
    "Behind the Back Wrist Curl": "Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl",
    "Hack Squat": "Hack_Squat",
    "Smith Machine Squat": "Smith_Machine_Squat",
    "Step Up": "Dumbbell_Step_Ups",
    "Reverse Lunge": "Barbell_Lunge",
    "Sissy Squat": "Weighted_Sissy_Squat",
    "Pistol Squat": "Kettlebell_Pistol_Squat",
    "Seated Leg Curl": "Seated_Leg_Curl",
    "Nordic Hamstring Curl": "Natural_Glute_Ham_Raise",
    "Single Leg RDL": "Stiff-Legged_Barbell_Deadlift",
    "Hip Abduction Machine": "Thigh_Abductor",
    "Cable Pull Through": "Pull_Through",
    "Kettlebell Swing": "One-Arm_Kettlebell_Swings",
    "Curtsy Lunge": "Barbell_Side_Split_Squat",
    "Calf Press on Leg Press": "Calf_Press_On_The_Leg_Press_Machine",
    "Single Leg Calf Raise": "Standing_Dumbbell_Calf_Raise",
    "Sit Up": "Sit-Up",
    "Bicycle Crunch": "Air_Bike",
    "Lying Leg Raise": "Flat_Bench_Lying_Leg_Raise",
    "Dead Bug": "Dead_Bug",
    "Cable Woodchopper": "Standing_Cable_Wood_Chop",
    "V-Up": "Butt-Ups",
    "Toe Touch": "Toe_Touchers",
    "Mountain Climber Twist": "Cross-Body_Crunch",
    "Elliptical": "Elliptical_Trainer",
    "Stair Climber": "Stairmaster",
    "Battle Ropes": "Battling_Ropes",
    "Box Jump": "Front_Box_Jump",
}


def _img(name: str) -> str:
    """Return the start-position illustration URL for an exercise."""
    slug = EXERCISE_IMAGE_SLUGS.get(name)
    if slug:
        return f"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{slug}/0.jpg"
    safe = name.replace(" ", "+")
    return f"https://placehold.co/400x300/c0152a/ffffff/png?text={safe}"


def _img2(name: str) -> str:
    """Return the end-position illustration URL for an exercise."""
    slug = EXERCISE_IMAGE_SLUGS.get(name)
    if slug:
        return f"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{slug}/1.jpg"
    return _img(name)


EXERCISES: List[Dict[str, Any]] = [
    # CHEST
    {"name": "Barbell Bench Press", "muscle_group": "chest", "equipment": "barbell", "instructions": "Lie on a flat bench, grip the bar slightly wider than shoulder width, lower to mid-chest and press up."},
    {"name": "Incline Dumbbell Press", "muscle_group": "chest", "equipment": "dumbbell", "instructions": "Set bench to 30-45°, press dumbbells from chest level upward, squeeze at the top."},
    {"name": "Dumbbell Bench Press", "muscle_group": "chest", "equipment": "dumbbell", "instructions": "Lie flat, lower dumbbells to chest level with controlled tempo, press straight up."},
    {"name": "Dumbbell Flyes", "muscle_group": "chest", "equipment": "dumbbell", "instructions": "Lie flat, arms slightly bent, open arms wide, then bring dumbbells back together over chest."},
    {"name": "Cable Crossover", "muscle_group": "chest", "equipment": "cable", "instructions": "Stand between pulleys, bring handles together in front of chest, squeeze the pecs."},
    {"name": "Push Up", "muscle_group": "chest", "equipment": "bodyweight", "instructions": "Plank position, lower chest to floor, push back up keeping core tight."},
    {"name": "Dips", "muscle_group": "chest", "equipment": "bodyweight", "instructions": "Lean forward to target chest, lower until upper arms are parallel to floor, press up."},
    {"name": "Machine Chest Press", "muscle_group": "chest", "equipment": "machine", "instructions": "Sit upright, press handles forward until arms extend, return slowly."},

    # BACK
    {"name": "Pull Up", "muscle_group": "back", "equipment": "bodyweight", "instructions": "Hang from bar with overhand grip, pull chin over the bar, lower with control."},
    {"name": "Lat Pulldown", "muscle_group": "back", "equipment": "cable", "instructions": "Sit and grip bar wide, pull down to upper chest, squeeze lats."},
    {"name": "Barbell Row", "muscle_group": "back", "equipment": "barbell", "instructions": "Hinge at hips, pull barbell to lower chest/upper abs, lower with control."},
    {"name": "Dumbbell Row", "muscle_group": "back", "equipment": "dumbbell", "instructions": "One knee on bench, row dumbbell to hip, squeeze shoulder blade."},
    {"name": "T-Bar Row", "muscle_group": "back", "equipment": "barbell", "instructions": "Hinged stance, pull T-bar to chest with neutral grip."},
    {"name": "Seated Cable Row", "muscle_group": "back", "equipment": "cable", "instructions": "Seated upright, pull handle to torso, squeeze back, return slowly."},
    {"name": "Deadlift", "muscle_group": "back", "equipment": "barbell", "instructions": "Bar over mid-foot, hinge & bend to grip, drive through legs to stand tall."},
    {"name": "Face Pull", "muscle_group": "back", "equipment": "cable", "instructions": "Cable at face height, pull rope to face with elbows high, squeeze rear delts."},

    # SHOULDERS
    {"name": "Overhead Press", "muscle_group": "shoulders", "equipment": "barbell", "instructions": "Bar at shoulders, press straight up until arms locked, lower under control."},
    {"name": "Dumbbell Shoulder Press", "muscle_group": "shoulders", "equipment": "dumbbell", "instructions": "Seated or standing, press dumbbells overhead, touch lightly at top."},
    {"name": "Lateral Raise", "muscle_group": "shoulders", "equipment": "dumbbell", "instructions": "Slight bend in elbows, raise dumbbells out to shoulder height, lower slowly."},
    {"name": "Front Raise", "muscle_group": "shoulders", "equipment": "dumbbell", "instructions": "Raise dumbbell to shoulder height in front of you, alternate arms."},
    {"name": "Rear Delt Fly", "muscle_group": "shoulders", "equipment": "dumbbell", "instructions": "Hinge forward, open arms wide leading with elbows, squeeze rear delts."},
    {"name": "Arnold Press", "muscle_group": "shoulders", "equipment": "dumbbell", "instructions": "Start with palms facing you, rotate as you press overhead."},
    {"name": "Upright Row", "muscle_group": "shoulders", "equipment": "barbell", "instructions": "Pull bar up to chest with elbows leading, keep close to body."},

    # BICEPS
    {"name": "Barbell Curl", "muscle_group": "biceps", "equipment": "barbell", "instructions": "Stand tall, curl bar to shoulders without swinging, lower under control."},
    {"name": "Dumbbell Curl", "muscle_group": "biceps", "equipment": "dumbbell", "instructions": "Curl dumbbells, supinate as you lift, squeeze biceps at top."},
    {"name": "Hammer Curl", "muscle_group": "biceps", "equipment": "dumbbell", "instructions": "Neutral grip throughout, curl to shoulders targeting brachialis."},
    {"name": "Preacher Curl", "muscle_group": "biceps", "equipment": "barbell", "instructions": "Arms over pad, curl bar up, lower slowly without locking elbow."},
    {"name": "Concentration Curl", "muscle_group": "biceps", "equipment": "dumbbell", "instructions": "Seated, elbow on inner thigh, curl dumbbell focusing on peak contraction."},
    {"name": "Cable Curl", "muscle_group": "biceps", "equipment": "cable", "instructions": "Stand at low pulley, curl handle to shoulders with constant tension."},

    # TRICEPS
    {"name": "Tricep Pushdown", "muscle_group": "triceps", "equipment": "cable", "instructions": "Elbows pinned to sides, press handle down until arms straight."},
    {"name": "Skull Crusher", "muscle_group": "triceps", "equipment": "barbell", "instructions": "Lie flat, lower bar to forehead, press back up keeping elbows fixed."},
    {"name": "Overhead Tricep Extension", "muscle_group": "triceps", "equipment": "dumbbell", "instructions": "Hold dumbbell overhead, lower behind head, extend back up."},
    {"name": "Close Grip Bench Press", "muscle_group": "triceps", "equipment": "barbell", "instructions": "Bench press with hands shoulder-width, focus on tricep extension."},
    {"name": "Tricep Dip", "muscle_group": "triceps", "equipment": "bodyweight", "instructions": "Upright torso, lower until elbows at 90°, press back up."},
    {"name": "Tricep Kickback", "muscle_group": "triceps", "equipment": "dumbbell", "instructions": "Hinge forward, extend dumbbell back until arm is straight."},

    # QUADS
    {"name": "Back Squat", "muscle_group": "quads", "equipment": "barbell", "instructions": "Bar across upper back, squat below parallel, drive through heels to stand."},
    {"name": "Front Squat", "muscle_group": "quads", "equipment": "barbell", "instructions": "Bar on front delts, elbows high, squat keeping torso upright."},
    {"name": "Leg Press", "muscle_group": "quads", "equipment": "machine", "instructions": "Feet shoulder-width on platform, lower until knees ~90°, press back."},
    {"name": "Leg Extension", "muscle_group": "quads", "equipment": "machine", "instructions": "Seated, extend legs until straight, squeeze quads, lower slowly."},
    {"name": "Walking Lunges", "muscle_group": "quads", "equipment": "dumbbell", "instructions": "Step forward into lunge, alternate legs continuing forward."},
    {"name": "Bulgarian Split Squat", "muscle_group": "quads", "equipment": "dumbbell", "instructions": "Rear foot on bench, lower into single-leg squat, press up."},
    {"name": "Goblet Squat", "muscle_group": "quads", "equipment": "dumbbell", "instructions": "Hold dumbbell at chest, squat between feet, stand tall."},

    # HAMSTRINGS
    {"name": "Romanian Deadlift", "muscle_group": "hamstrings", "equipment": "barbell", "instructions": "Hinge at hips with slight knee bend, lower bar along thighs, return."},
    {"name": "Lying Leg Curl", "muscle_group": "hamstrings", "equipment": "machine", "instructions": "Face down, curl heels toward glutes, squeeze hamstrings."},
    {"name": "Stiff Leg Deadlift", "muscle_group": "hamstrings", "equipment": "dumbbell", "instructions": "Keep legs straight, hinge forward, feel hamstring stretch, return."},
    {"name": "Glute Ham Raise", "muscle_group": "hamstrings", "equipment": "bodyweight", "instructions": "On GHR machine, lower body under control, use hamstrings to return."},

    # GLUTES
    {"name": "Barbell Hip Thrust", "muscle_group": "glutes", "equipment": "barbell", "instructions": "Upper back on bench, bar over hips, drive hips up squeezing glutes."},
    {"name": "Glute Bridge", "muscle_group": "glutes", "equipment": "bodyweight", "instructions": "Lie flat, drive hips up squeezing glutes, hold and lower."},
    {"name": "Cable Glute Kickback", "muscle_group": "glutes", "equipment": "cable", "instructions": "Cable attached to ankle, kick leg back squeezing glute."},
    {"name": "Sumo Deadlift", "muscle_group": "glutes", "equipment": "barbell", "instructions": "Wide stance, toes out, grip bar inside legs, drive up."},

    # CALVES
    {"name": "Standing Calf Raise", "muscle_group": "calves", "equipment": "machine", "instructions": "Raise heels as high as possible, squeeze calves, lower slowly."},
    {"name": "Seated Calf Raise", "muscle_group": "calves", "equipment": "machine", "instructions": "Seated with pad on knees, raise heels, squeeze, lower."},
    {"name": "Donkey Calf Raise", "muscle_group": "calves", "equipment": "machine", "instructions": "Hinged forward, raise on toes, squeeze calves at top."},

    # CORE
    {"name": "Plank", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Forearms on floor, body straight line, hold position."},
    {"name": "Crunches", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Lie flat with knees bent, curl shoulders off floor squeezing abs."},
    {"name": "Russian Twist", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Seated with feet up, rotate torso side to side."},
    {"name": "Hanging Leg Raise", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Hang from bar, raise legs to 90° or higher, lower under control."},
    {"name": "Cable Crunch", "muscle_group": "core", "equipment": "cable", "instructions": "Kneel with rope at face, crunch down squeezing abs."},
    {"name": "Ab Wheel Rollout", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Kneel with ab wheel, roll forward keeping abs tight, return."},
    {"name": "Side Plank", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Side position on forearm, hips up, hold; switch sides."},

    # CARDIO
    {"name": "Treadmill Run", "muscle_group": "cardio", "equipment": "machine", "instructions": "Maintain steady pace or alternate intervals as desired."},
    {"name": "Stationary Bike", "muscle_group": "cardio", "equipment": "machine", "instructions": "Adjust seat and resistance, cycle at consistent cadence."},
    {"name": "Rowing Machine", "muscle_group": "cardio", "equipment": "machine", "instructions": "Drive legs, lean back, pull handle to chest; reverse to return."},
    {"name": "Jump Rope", "muscle_group": "cardio", "equipment": "bodyweight", "instructions": "Light bounce on balls of feet, wrist rotation for swing."},
    {"name": "Burpees", "muscle_group": "cardio", "equipment": "bodyweight", "instructions": "Squat down, jump back to plank, push-up, jump forward, jump up."},
    {"name": "Mountain Climbers", "muscle_group": "cardio", "equipment": "bodyweight", "instructions": "Plank position, alternate driving knees toward chest rapidly."},

    # ─────────── EXPANDED LIBRARY ───────────
    # CHEST
    {"name": "Incline Barbell Bench Press", "muscle_group": "chest", "equipment": "barbell", "instructions": "Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked."},
    {"name": "Decline Barbell Bench Press", "muscle_group": "chest", "equipment": "barbell", "instructions": "Secure your legs at the end of the decline bench and slowly lay down on the bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you wit"},
    {"name": "Pec Deck Fly", "muscle_group": "chest", "equipment": "machine", "instructions": "Sit on the machine with your back flat on the pad. Take hold of the handles."},
    {"name": "Incline Cable Fly", "muscle_group": "chest", "equipment": "cable", "instructions": "To get yourself into the starting position, set the pulleys at the floor level (lowest level possible on the machine that is below your torso). Place an incline bench (set at 45 degrees) in between the pulleys, select a weight on each one and grab a pulley on each hand."},
    {"name": "Decline Push Up", "muscle_group": "chest", "equipment": "bodyweight", "instructions": "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Move your feet up to a box or bench."},
    {"name": "Smith Machine Bench Press", "muscle_group": "chest", "equipment": "machine", "instructions": "Place a flat bench underneath the smith machine. Now place the barbell at a height that you can reach when lying down and your arms are almost fully extended."},

    # BACK
    {"name": "Chin Up", "muscle_group": "back", "equipment": "bodyweight", "instructions": "Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and stic"},
    {"name": "Straight Arm Pulldown", "muscle_group": "back", "equipment": "cable", "instructions": "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so."},
    {"name": "Close Grip Lat Pulldown", "muscle_group": "back", "equipment": "cable", "instructions": "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height."},
    {"name": "Chest Supported Row", "muscle_group": "back", "equipment": "machine", "instructions": "Set the barbell attached to the smith machine to a height that is about 2 inches below your knees. Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor."},
    {"name": "Machine Row", "muscle_group": "back", "equipment": "machine", "instructions": "Load an appropriate weight onto the pins and adjust the seat height so that you can just reach the handles above you. Adjust the knee pad to help keep you down."},
    {"name": "Rack Pull", "muscle_group": "back", "equipment": "barbell", "instructions": "Set up in a power rack with the bar on the pins. The pins should be set to the desired point; just below the knees, just above, or in the mid thigh position."},
    {"name": "Pendlay Row", "muscle_group": "back", "equipment": "barbell", "instructions": "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up."},
    {"name": "Inverted Row", "muscle_group": "back", "equipment": "bodyweight", "instructions": "Position a bar in a rack to about waist height. You can also use a smith machine."},

    # LOWER BACK
    {"name": "Back Extension", "muscle_group": "lower back", "equipment": "bodyweight", "instructions": "Lie face down on a hyperextension bench, tucking your ankles securely under the footpads. Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction."},
    {"name": "Good Morning", "muscle_group": "lower back", "equipment": "barbell", "instructions": "Begin with a bar on a rack at shoulder height. Rack the bar across the rear of your shoulders as you would a power squat, not on top of your shoulders."},
    {"name": "Superman", "muscle_group": "lower back", "equipment": "bodyweight", "instructions": "To begin, lie straight and face down on the floor or exercise mat. Your arms should be fully extended in front of you."},

    # TRAPS
    {"name": "Barbell Shrug", "muscle_group": "traps", "equipment": "barbell", "instructions": "Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart."},
    {"name": "Dumbbell Shrug", "muscle_group": "traps", "equipment": "dumbbell", "instructions": "Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides. Lift the dumbbells by elevating the shoulders as high as possible while you exhale."},
    {"name": "Cable Shrug", "muscle_group": "traps", "equipment": "cable", "instructions": "Grasp a cable bar attachment that is attached to a low pulley with a shoulder width or slightly wider overhand (palms facing down) grip. Stand erect close to the pulley with your arms extended in front of you holding the bar."},

    # SHOULDERS
    {"name": "Machine Shoulder Press", "muscle_group": "shoulders", "equipment": "machine", "instructions": "Sit down on the Shoulder Press Machine and select the weight. Grab the handles to your sides as you keep the elbows bent and in line with your torso."},
    {"name": "Cable Lateral Raise", "muscle_group": "shoulders", "equipment": "cable", "instructions": "Stand in the middle of two low pulleys that are opposite to each other and place a flat bench right behind you (in perpendicular fashion to you; the narrow edge of the bench should be the one behind you). Select the weight to be used on each pulley."},
    {"name": "Reverse Pec Deck", "muscle_group": "shoulders", "equipment": "machine", "instructions": "Adjust the handles so that they are fully to the rear. Make an appropriate weight selection and adjust the seat height so the handles are at shoulder level."},
    {"name": "Push Press", "muscle_group": "shoulders", "equipment": "barbell", "instructions": "See demonstration."},
    {"name": "Seated Barbell Press", "muscle_group": "shoulders", "equipment": "barbell", "instructions": "Sit on a Military Press Bench with a bar behind your head and either have a spotter give you the bar (better on the rotator cuff this way) or pick it up yourself carefully with a pronated grip (palms facing forward). Tip: Your grip should be wider than shoulder width and it shoul"},

    # BICEPS
    {"name": "EZ Bar Curl", "muscle_group": "biceps", "equipment": "barbell", "instructions": "Stand up straight while holding an EZ curl bar at the wide outer handle. The palms of your hands should be facing forward and slightly tilted inward due to the shape of the bar."},
    {"name": "Incline Dumbbell Curl", "muscle_group": "biceps", "equipment": "dumbbell", "instructions": "Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward."},
    {"name": "Spider Curl", "muscle_group": "biceps", "equipment": "barbell", "instructions": "Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off."},
    {"name": "Machine Bicep Curl", "muscle_group": "biceps", "equipment": "machine", "instructions": "Adjust the seat to the appropriate height and make your weight selection. Place your upper arms against the pads and grasp the handles."},

    # TRICEPS
    {"name": "Diamond Push Up", "muscle_group": "triceps", "equipment": "bodyweight", "instructions": "Lie on the floor face down and place your hands closer than shoulder width for a close hand position. Make sure that you are holding your torso up at arms' length."},
    {"name": "Cable Rope Pushdown", "muscle_group": "triceps", "equipment": "cable", "instructions": "Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other). Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor."},
    {"name": "Machine Tricep Extension", "muscle_group": "triceps", "equipment": "machine", "instructions": "Adjust the seat to the appropriate height and make your weight selection. Place your upper arms against the pads and grasp the handles."},
    {"name": "Bench Dip", "muscle_group": "triceps", "equipment": "bodyweight", "instructions": "For this exercise you will need to place a bench behind your back. With the bench perpendicular to your body, and while looking away from it, hold on to the bench on its edge with the hands fully extended, separated at shoulder width."},

    # FOREARMS
    {"name": "Wrist Curl", "muscle_group": "forearms", "equipment": "barbell", "instructions": "Start out by placing a barbell on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench."},
    {"name": "Reverse Wrist Curl", "muscle_group": "forearms", "equipment": "barbell", "instructions": "Start out by placing a barbell on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench."},
    {"name": "Reverse Barbell Curl", "muscle_group": "forearms", "equipment": "barbell", "instructions": "Stand up with your torso upright while holding a barbell at shoulder width with the elbows close to the torso. The palm of your hands should be facing down (pronated grip)."},
    {"name": "Farmers Walk", "muscle_group": "forearms", "equipment": "dumbbell", "instructions": "There are various implements that can be used for the farmers walk. These can also be performed with heavy dumbbells or short bars if these implements aren't available."},
    {"name": "Behind the Back Wrist Curl", "muscle_group": "forearms", "equipment": "barbell", "instructions": "Start by standing straight and holding a barbell behind your glutes at arm's length while using a pronated grip (palms will be facing back away from the glutes) and having your hands shoulder width apart from each other. You should be looking straight forward while your feet are "},

    # QUADS
    {"name": "Hack Squat", "muscle_group": "quads", "equipment": "machine", "instructions": "Place the back of your torso against the back pad of the machine and hook your shoulders under the shoulder pads provided. Position your legs in the platform using a shoulder width medium stance with the toes slightly pointed out."},
    {"name": "Smith Machine Squat", "muscle_group": "quads", "equipment": "machine", "instructions": "To begin, first set the bar on the height that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it."},
    {"name": "Step Up", "muscle_group": "quads", "equipment": "dumbbell", "instructions": "Stand up straight while holding a dumbbell on each hand (palms facing the side of your legs). Place the right foot on the elevated platform."},
    {"name": "Reverse Lunge", "muscle_group": "quads", "equipment": "barbell", "instructions": "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just below shoulder level."},
    {"name": "Sissy Squat", "muscle_group": "quads", "equipment": "bodyweight", "instructions": "Standing upright, with feet at shoulder width and toes raised, use one hand to hold onto the beams of a squat rack and the opposite arm to hold a plate on top of your chest. This is your starting position."},
    {"name": "Pistol Squat", "muscle_group": "quads", "equipment": "bodyweight", "instructions": "Pick up a kettlebell with two hands and hold it by the horns. Hold one leg off of the floor and squat down on the other."},

    # HAMSTRINGS
    {"name": "Seated Leg Curl", "muscle_group": "hamstrings", "equipment": "machine", "instructions": "Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad. Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees."},
    {"name": "Nordic Hamstring Curl", "muscle_group": "hamstrings", "equipment": "bodyweight", "instructions": "Using the leg pad of a lat pulldown machine or a preacher bench, position yourself so that your ankles are under the pads, knees on the seat, and you are facing away from the machine. You should be upright and maintaining good posture."},
    {"name": "Single Leg RDL", "muscle_group": "hamstrings", "equipment": "dumbbell", "instructions": "Grasp a bar using an overhand grip (palms facing down). You may need some wrist wraps if using a significant amount of weight."},

    # GLUTES
    {"name": "Hip Abduction Machine", "muscle_group": "glutes", "equipment": "machine", "instructions": "To begin, sit down on the abductor machine and select a weight you are comfortable with. When your legs are positioned properly, grip the handles on each side."},
    {"name": "Cable Pull Through", "muscle_group": "glutes", "equipment": "cable", "instructions": "Begin standing a few feet in front of a low pulley with a rope or handle attached. Face away from the machine, straddling the cable, with your feet set wide apart."},
    {"name": "Kettlebell Swing", "muscle_group": "glutes", "equipment": "kettlebell", "instructions": "See demonstration."},
    {"name": "Curtsy Lunge", "muscle_group": "glutes", "equipment": "dumbbell", "instructions": "Stand up straight while holding a barbell placed on the back of your shoulders (slightly below the neck). Your feet should be placed wide apart with the foot of the lead leg angled out to the side."},

    # CALVES
    {"name": "Calf Press on Leg Press", "muscle_group": "calves", "equipment": "machine", "instructions": "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully e"},
    {"name": "Single Leg Calf Raise", "muscle_group": "calves", "equipment": "dumbbell", "instructions": "Stand with your torso upright holding two dumbbells in your hands by your sides. Place the ball of the foot on a sturdy and stable wooden board (that is around 2-3 inches tall) while your heels extend off and touch the floor."},

    # CORE
    {"name": "Sit Up", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees."},
    {"name": "Bicycle Crunch", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Lie flat on the floor with your lower back pressed to the ground. For this exercise, you will need to put your hands beside your head."},
    {"name": "Lying Leg Raise", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Lie with your back flat on a bench and your legs extended in front of you off the end. Place your hands either under your glutes with your palms down or by the sides holding on to the bench."},
    {"name": "Dead Bug", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Begin lying on your back with your hands extended above you toward the ceiling. Bring your feet, knees, and hips up to 90 degrees."},
    {"name": "Cable Woodchopper", "muscle_group": "core", "equipment": "cable", "instructions": "Connect a standard handle to a tower, and move the cable to the highest pulley position. With your side to the cable, grab the handle with one hand and step away from the tower."},
    {"name": "V-Up", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Begin a pushup position but with your elbows on the ground and resting on your forearms. Your arms should be bent at a 90 degree angle."},
    {"name": "Toe Touch", "muscle_group": "core", "equipment": "bodyweight", "instructions": "To begin, lie down on the floor or an exercise mat with your back pressed against the floor. Your arms should be lying across your sides with the palms facing down."},
    {"name": "Mountain Climber Twist", "muscle_group": "core", "equipment": "bodyweight", "instructions": "Lie flat on your back and bend your knees about 60 degrees. Keep your feet flat on the floor and place your hands loosely behind your head."},

    # CARDIO
    {"name": "Elliptical", "muscle_group": "cardio", "equipment": "machine", "instructions": "To begin, step onto the elliptical and select the desired option from the menu. Most ellipticals have a manual setting, or you can select a program to run."},
    {"name": "Stair Climber", "muscle_group": "cardio", "equipment": "machine", "instructions": "To begin, step onto the stairmaster and select the desired option from the menu. You can choose a manual setting, or you can select a program to run."},
    {"name": "Battle Ropes", "muscle_group": "cardio", "equipment": "bodyweight", "instructions": "For this exercise you will need a heavy rope anchored at its center 15-20 feet away. Standing in front of the rope, take an end in each hand with your arms extended at your side."},
    {"name": "Box Jump", "muscle_group": "cardio", "equipment": "bodyweight", "instructions": "Begin with a box of an appropriate height 1-2 feet in front of you. Stand with your feet should width apart."},
]

# Animated demonstration videos (musclewiki.com CDN) — name -> mp4 url.
VIDEO_URLS = {
    "Decline Barbell Bench Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-decline-bench-press-front.mp4",
    "Cable Woodchopper": "https://media.musclewiki.com/media/uploads/videos/branded/male-cable-woodchopper-front.mp4",
    "Incline Cable Fly": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-incline-chest-fly-side.mp4",
    "Close Grip Lat Pulldown": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-narrow-pulldown-front.mp4",
    "Ab Wheel Rollout": "https://media.musclewiki.com/media/uploads/videos/branded/male-trx-ab-rollout-front.mp4",
    "Arnold Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-arnold-press-front.mp4",
    "Back Extension": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-back-extension-front.mp4",
    "Back Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-squat-side.mp4",
    "Barbell Bench Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-bench-press-front.mp4",
    "Barbell Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-curl-front.mp4",
    "Barbell Hip Thrust": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-hip-thrust-front.mp4",
    "Barbell Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-bent-over-row-front.mp4",
    "Barbell Shrug": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-shrug-front.mp4",
    "Behind the Back Wrist Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-behind-the-back-wrist-curl-front.mp4",
    "Bench Dip": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bench-dips-front.mp4",
    "Bicycle Crunch": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bicycle-crunch-side.mp4",
    "Box Jump": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-box-jump-side.mp4",
    "Bulgarian Split Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-bulgarian-split-squat-front.mp4",
    "Burpees": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-burpee-front.mp4",
    "Cable Crossover": "https://media.musclewiki.com/media/uploads/videos/branded/male-cable-pec-fly-front.mp4",
    "Cable Crunch": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-rope-kneeling-crunch-side.mp4",
    "Cable Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-bilateral-bayesian-curl-side.mp4",
    "Cable Glute Kickback": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-standing-kickback-front.mp4",
    "Cable Lateral Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-lateral-raise-front.mp4",
    "Cable Pull Through": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-pull-through-side.mp4",
    "Cable Rope Pushdown": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-push-down-side.mp4",
    "Cable Shrug": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-30-degree-shrug-front.mp4",
    "Calf Press on Leg Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-horizontal-leg-press-calf-raise-side.mp4",
    "Chest Supported Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-chest-supported-t-bar-row-side.mp4",
    "Chin Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-chinup-front.mp4",
    "Close Grip Bench Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-close-grip-bench-press-side.mp4",
    "Concentration Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-concentration-curl-front.mp4",
    "Crunches": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-crunch-front.mp4",
    "Curtsy Lunge": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-goblet-curtsy-lunge-front.mp4",
    "Dead Bug": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-dead-bug-side.mp4",
    "Deadlift": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-deadlift-front.mp4",
    "Decline Push Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-decline-push-up-front.mp4",
    "Diamond Push Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-diamond-push-ups-front.mp4",
    "Dips": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-assisted-parralel-bar-dips-front.mp4",
    "Donkey Calf Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-donkey-calf-raise-front.mp4",
    "Dumbbell Bench Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-bench-press-front_y8zKZJl.mp4",
    "Dumbbell Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-curl-front.mp4",
    "Dumbbell Flyes": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-chest-fly-front.mp4",
    "Dumbbell Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-row-unilateral-front.mp4",
    "Dumbbell Shoulder Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-seated-overhead-press-front.mp4",
    "Dumbbell Shrug": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-shrug-front.mp4",
    "EZ Bar Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-ez-bar-curl-side.mp4",
    "Elliptical": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-elliptical-side.mp4",
    "Face Pull": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-face-pulls-front.mp4",
    "Farmers Walk": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-farmer-walk-side.mp4",
    "Front Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-front-raise-side.mp4",
    "Front Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-front-squat-bodybuilding-side.mp4",
    "Glute Bridge": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-glute-bridge-side.mp4",
    "Glute Ham Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-glute-ham-raise-front.mp4",
    "Goblet Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-goblet-squat-front.mp4",
    "Good Morning": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-high-bar-good-morning-front.mp4",
    "Hack Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-hack-squat-side.mp4",
    "Hammer Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-hammer-curl-front.mp4",
    "Hanging Leg Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-hanging-knee-raises-front.mp4",
    "Hip Abduction Machine": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-hip-abduction-front.mp4",
    "Incline Barbell Bench Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-incline-bench-press-front.mp4",
    "Incline Dumbbell Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-incline-curl-front.mp4",
    "Incline Dumbbell Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-incline-bench-press-front_q2q0T12.mp4",
    "Inverted Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-reverse-row-front.mp4",
    "Jump Rope": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-jump-rope-front.mp4",
    "Kettlebell Swing": "https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-swing-front.mp4",
    "Lat Pulldown": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-pulldown-front.mp4",
    "Lateral Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-lateral-raise-front.mp4",
    "Leg Extension": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-leg-extension-front.mp4",
    "Leg Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-leg-press-side.mp4",
    "Lying Leg Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-hamstring-curl-front.mp4",
    "Lying Leg Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-laying-leg-raises-front.mp4",
    "Machine Bicep Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-seated-plate-loaded-preacher-curl-side.mp4",
    "Machine Chest Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-chest-press-side.mp4",
    "Machine Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-seated-cable-row-front.mp4",
    "Machine Shoulder Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-front-military-press-side.mp4",
    "Machine Tricep Extension": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-overhead-tricep-extension-side.mp4",
    "Mountain Climber Twist": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-elbow-plank-mountain-climber-side.mp4",
    "Mountain Climbers": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-mountain-climber-front.mp4",
    "Nordic Hamstring Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-nordic-hamstring-curl-front.mp4",
    "Overhead Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-overhead-press-front.mp4",
    "Overhead Tricep Extension": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-overhead-tricep-extension-side.mp4",
    "Pec Deck Fly": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-pec-fly-side.mp4",
    "Pendlay Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-pronated-pendlay-row-front.mp4",
    "Plank": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-forearm-plank-front.mp4",
    "Preacher Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-preacher-curl-front.mp4",
    "Pull Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-pullup-front.mp4",
    "Push Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-push-press-side.mp4",
    "Push Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-push-up-front.mp4",
    "Rack Pull": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-rack-pull-front.mp4",
    "Rear Delt Fly": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-rear-delt-fly-side.mp4",
    "Reverse Barbell Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-reverse-curl-front.mp4",
    "Reverse Lunge": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-reverse-lunge-front.mp4",
    "Reverse Pec Deck": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-reverse-fly-front.mp4",
    "Reverse Wrist Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Kettlebells-kettlebell-wrist-extension-front.mp4",
    "Romanian Deadlift": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-romanian-deadlift-side_dnNh5UH.mp4",
    "Rowing Machine": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-cardio-row-erg-rower-front.mp4",
    "Russian Twist": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-russian-twist-front.mp4",
    "Seated Barbell Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-behind-the-neck-seated-overhead-press-front.mp4",
    "Seated Cable Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-seated-cable-row-front.mp4",
    "Seated Calf Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-seated-calf-raise-front.mp4",
    "Seated Leg Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-seated-leg-curl-front.mp4",
    "Side Plank": "https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-elbow-side-plank-front.mp4",
    "Single Leg Calf Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-single-leg-calf-raise-front.mp4",
    "Single Leg RDL": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-single-leg-stiff-leg-deadlift-side.mp4",
    "Sissy Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-sissy-squat-side.mp4",
    "Sit Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-landmine-sit-up-side.mp4",
    "Skull Crusher": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-skullcrusher-front.mp4",
    "Smith Machine Bench Press": "https://media.musclewiki.com/media/uploads/videos/branded/male-Smithmachine-bench-press-side.mp4",
    "Smith Machine Squat": "https://media.musclewiki.com/media/uploads/videos/branded/male-Smithmachine-squat-side.mp4",
    "Spider Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-spider-curl-front.mp4",
    "Stair Climber": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-stair-climber-side.mp4",
    "Standing Calf Raise": "https://media.musclewiki.com/media/uploads/videos/branded/male-machine-standing-calf-raises-front.mp4",
    "Stationary Bike": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-cardio-assault-bike-front.mp4",
    "Step Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-step-up-side.mp4",
    "Stiff Leg Deadlift": "https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-stiff-leg-deadlift-front.mp4",
    "Straight Arm Pulldown": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cables-cable-straight-arm-pull-in-side.mp4",
    "Sumo Deadlift": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-sumo-deadlift-side_5lcmI1F.mp4",
    "Superman": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-superman-front.mp4",
    "T-Bar Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-landmine-t-bar-rows-side.mp4",
    "Treadmill Run": "https://media.musclewiki.com/media/uploads/videos/branded/male-Cardio-treadmill-jog-front.mp4",
    "Tricep Dip": "https://media.musclewiki.com/media/uploads/videos/branded/male-Machine-machine-assisted-parralel-bar-dips-front.mp4",
    "Tricep Kickback": "https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-tricep-kickback-front.mp4",
    "Tricep Pushdown": "https://media.musclewiki.com/media/uploads/videos/branded/male-cable-push-downs-front.mp4",
    "Upright Row": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-upright-row-side.mp4",
    "V-Up": "https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-stability-ball-v-up-pass-front.mp4",
    "Walking Lunges": "https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-forward-lunge-side.mp4",
    "Wrist Curl": "https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-wrist-curl-front.mp4",
}


# Secondary muscles worked, per exercise (free-exercise-db).
SECONDARY_MUSCLES = {
    "Ab Wheel Rollout": ["shoulders"],
    "Arnold Press": ["triceps"],
    "Back Extension": ["glutes", "hamstrings"],
    "Back Squat": ["calves", "glutes", "hamstrings", "lower back"],
    "Barbell Bench Press": ["shoulders", "triceps"],
    "Barbell Curl": ["forearms"],
    "Barbell Hip Thrust": ["calves", "hamstrings"],
    "Barbell Row": ["biceps", "lats", "shoulders"],
    "Battle Ropes": ["chest", "forearms"],
    "Bench Dip": ["chest", "shoulders"],
    "Box Jump": ["abductors", "adductors", "calves", "glutes", "quadriceps"],
    "Bulgarian Split Squat": ["calves", "glutes", "quadriceps"],
    "Burpees": ["shoulders", "triceps"],
    "Cable Crossover": ["shoulders"],
    "Cable Glute Kickback": ["hamstrings"],
    "Cable Lateral Raise": ["middle back", "traps"],
    "Cable Pull Through": ["hamstrings", "lower back"],
    "Cable Woodchopper": ["shoulders"],
    "Chest Supported Row": ["biceps", "lats", "shoulders"],
    "Chin Up": ["biceps", "forearms", "middle back"],
    "Close Grip Bench Press": ["chest", "shoulders"],
    "Close Grip Lat Pulldown": ["biceps", "middle back", "shoulders"],
    "Concentration Curl": ["forearms"],
    "Curtsy Lunge": ["calves", "hamstrings", "lower back"],
    "Deadlift": ["calves", "forearms", "glutes", "hamstrings", "lats", "middle back", "quadriceps", "traps"],
    "Decline Barbell Bench Press": ["shoulders", "triceps"],
    "Decline Push Up": ["shoulders", "triceps"],
    "Diamond Push Up": ["chest", "shoulders"],
    "Dips": ["shoulders", "triceps"],
    "Dumbbell Bench Press": ["shoulders", "triceps"],
    "Dumbbell Curl": ["forearms"],
    "Dumbbell Row": ["biceps", "lats", "shoulders"],
    "Dumbbell Shoulder Press": ["triceps"],
    "Elliptical": ["calves", "glutes", "hamstrings"],
    "Face Pull": ["middle back"],
    "Farmers Walk": ["abdominals", "glutes", "hamstrings", "lower back", "quadriceps", "traps"],
    "Front Squat": ["calves", "glutes", "hamstrings"],
    "Glute Bridge": ["calves", "hamstrings"],
    "Glute Ham Raise": ["calves", "glutes"],
    "Goblet Squat": ["calves", "glutes", "hamstrings", "shoulders"],
    "Good Morning": ["abdominals", "glutes", "lower back"],
    "Hack Squat": ["calves", "glutes", "hamstrings"],
    "Hip Abduction Machine": ["glutes"],
    "Incline Barbell Bench Press": ["shoulders", "triceps"],
    "Incline Cable Fly": ["shoulders"],
    "Incline Dumbbell Press": ["shoulders", "triceps"],
    "Inverted Row": ["lats"],
    "Jump Rope": ["calves", "hamstrings"],
    "Kettlebell Swing": ["calves", "glutes", "lower back", "shoulders"],
    "Lat Pulldown": ["biceps", "middle back", "shoulders"],
    "Leg Press": ["calves", "glutes", "hamstrings"],
    "Machine Chest Press": ["shoulders", "triceps"],
    "Machine Row": ["lats"],
    "Machine Shoulder Press": ["triceps"],
    "Mountain Climbers": ["chest", "hamstrings", "shoulders"],
    "Nordic Hamstring Curl": ["calves", "glutes", "lower back"],
    "Overhead Press": ["triceps"],
    "Pendlay Row": ["biceps", "lats", "shoulders"],
    "Pistol Squat": ["calves", "glutes", "hamstrings", "shoulders"],
    "Pull Up": ["biceps", "middle back"],
    "Push Press": ["quadriceps", "triceps"],
    "Push Up": ["shoulders", "triceps"],
    "Rack Pull": ["forearms", "glutes", "hamstrings", "traps"],
    "Reverse Barbell Curl": ["forearms"],
    "Reverse Lunge": ["calves", "glutes", "hamstrings"],
    "Romanian Deadlift": ["calves", "glutes", "lower back"],
    "Rowing Machine": ["biceps", "calves", "glutes", "hamstrings", "lower back", "middle back"],
    "Russian Twist": ["lower back"],
    "Seated Barbell Press": ["triceps"],
    "Seated Cable Row": ["biceps", "lats", "shoulders"],
    "Side Plank": ["abdominals", "shoulders", "triceps"],
    "Single Leg RDL": ["glutes", "lower back"],
    "Sissy Squat": ["calves", "glutes", "hamstrings"],
    "Skull Crusher": ["forearms"],
    "Smith Machine Bench Press": ["shoulders", "triceps"],
    "Smith Machine Squat": ["calves", "glutes", "hamstrings", "lower back"],
    "Stair Climber": ["calves", "glutes", "hamstrings"],
    "Step Up": ["calves", "glutes", "hamstrings"],
    "Stiff Leg Deadlift": ["glutes", "lower back"],
    "Sumo Deadlift": ["adductors", "forearms", "glutes", "lower back", "middle back", "quadriceps", "traps"],
    "Superman": ["glutes", "hamstrings"],
    "T-Bar Row": ["biceps", "lats"],
    "Treadmill Run": ["calves", "glutes", "hamstrings"],
    "Tricep Dip": ["chest", "shoulders"],
    "Upright Row": ["shoulders"],
    "Walking Lunges": ["calves", "glutes", "hamstrings"],
}


# Attach image_url + image_url_end + video_url + secondary_muscles to every exercise
for _ex in EXERCISES:
    _ex["image_url"] = _img(_ex["name"])
    _ex["image_url_end"] = _img2(_ex["name"])
    _ex["video_url"] = VIDEO_URLS.get(_ex["name"])
    _ex["secondary_muscles"] = SECONDARY_MUSCLES.get(_ex["name"], [])


# Helper to build a routine quickly
def _r(name: str, exercise_names: List[str]) -> Dict[str, Any]:
    return {"name": name, "exercises": exercise_names}


PROGRAMS: List[Dict[str, Any]] = [
    # ─────────── BEGINNER ───────────
    {
        "name": "Full Body 3x",
        "level": "beginner",
        "goal": "strength",
        "equipment": "barbell",
        "duration_weeks": 8,
        "description": "Classic 3-day full body routine. Compound focus, ideal for new lifters.",
        "routines": [
            _r("Full Body A", ["Back Squat", "Barbell Bench Press", "Barbell Row", "Plank"]),
            _r("Full Body B", ["Deadlift", "Overhead Press", "Pull Up", "Crunches"]),
            _r("Full Body C", ["Back Squat", "Incline Dumbbell Press", "Lat Pulldown", "Russian Twist"]),
        ],
    },
    {
        "name": "Beginner PPL",
        "level": "beginner",
        "goal": "hypertrophy",
        "equipment": "barbell",
        "duration_weeks": 8,
        "description": "Push/Pull/Legs split for beginners. 3 days per week.",
        "routines": [
            _r("Push Day", ["Barbell Bench Press", "Overhead Press", "Tricep Pushdown", "Lateral Raise"]),
            _r("Pull Day", ["Barbell Row", "Lat Pulldown", "Barbell Curl", "Face Pull"]),
            _r("Leg Day", ["Back Squat", "Romanian Deadlift", "Leg Extension", "Standing Calf Raise"]),
        ],
    },
    {
        "name": "Home Bodyweight",
        "level": "beginner",
        "goal": "general",
        "equipment": "bodyweight",
        "duration_weeks": 6,
        "description": "No-equipment full body routine you can do anywhere.",
        "routines": [
            _r("Upper Body", ["Push Up", "Pull Up", "Tricep Dip", "Plank"]),
            _r("Lower Body", ["Glute Bridge", "Walking Lunges", "Goblet Squat", "Side Plank"]),
            _r("Core & Cardio", ["Plank", "Russian Twist", "Mountain Climbers", "Burpees"]),
        ],
    },
    {
        "name": "Dumbbell Only Beginner",
        "level": "beginner",
        "goal": "hypertrophy",
        "equipment": "dumbbell",
        "duration_weeks": 8,
        "description": "Built around dumbbells. Perfect for home gyms.",
        "routines": [
            _r("Upper Body", ["Dumbbell Bench Press", "Dumbbell Row", "Dumbbell Shoulder Press", "Dumbbell Curl"]),
            _r("Lower Body", ["Goblet Squat", "Stiff Leg Deadlift", "Bulgarian Split Squat", "Standing Calf Raise"]),
            _r("Full Body", ["Dumbbell Bench Press", "Dumbbell Row", "Walking Lunges", "Plank"]),
        ],
    },

    # ─────────── INTERMEDIATE ───────────
    {
        "name": "Intermediate PPL",
        "level": "intermediate",
        "goal": "hypertrophy",
        "equipment": "barbell",
        "duration_weeks": 12,
        "description": "Push, Pull, Legs split run 6 days per week. Volume + intensity.",
        "routines": [
            _r("Push", ["Barbell Bench Press", "Overhead Press", "Incline Dumbbell Press", "Lateral Raise", "Tricep Pushdown", "Skull Crusher"]),
            _r("Pull", ["Deadlift", "Pull Up", "Barbell Row", "Face Pull", "Barbell Curl", "Hammer Curl"]),
            _r("Legs", ["Back Squat", "Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Standing Calf Raise", "Hanging Leg Raise"]),
        ],
    },
    {
        "name": "Upper / Lower Split",
        "level": "intermediate",
        "goal": "strength",
        "equipment": "barbell",
        "duration_weeks": 10,
        "description": "4-day upper/lower split balancing strength and size.",
        "routines": [
            _r("Upper Power", ["Barbell Bench Press", "Barbell Row", "Overhead Press", "Pull Up"]),
            _r("Lower Power", ["Back Squat", "Romanian Deadlift", "Leg Press", "Standing Calf Raise"]),
            _r("Upper Hypertrophy", ["Incline Dumbbell Press", "Seated Cable Row", "Lateral Raise", "Cable Curl", "Tricep Pushdown"]),
            _r("Lower Hypertrophy", ["Front Squat", "Lying Leg Curl", "Walking Lunges", "Seated Calf Raise"]),
        ],
    },
    {
        "name": "Bro Split 5-Day",
        "level": "intermediate",
        "goal": "hypertrophy",
        "equipment": "barbell",
        "duration_weeks": 10,
        "description": "Classic body-part split — one muscle group per day.",
        "routines": [
            _r("Chest Day", ["Barbell Bench Press", "Incline Dumbbell Press", "Dumbbell Flyes", "Cable Crossover", "Dips"]),
            _r("Back Day", ["Deadlift", "Pull Up", "Barbell Row", "Seated Cable Row", "Face Pull"]),
            _r("Shoulder Day", ["Overhead Press", "Lateral Raise", "Rear Delt Fly", "Front Raise", "Upright Row"]),
            _r("Arm Day", ["Barbell Curl", "Hammer Curl", "Skull Crusher", "Tricep Pushdown", "Preacher Curl"]),
            _r("Leg Day", ["Back Squat", "Leg Press", "Lying Leg Curl", "Walking Lunges", "Standing Calf Raise"]),
        ],
    },
    {
        "name": "PPL + Cardio Aesthetic",
        "level": "intermediate",
        "goal": "aesthetic",
        "equipment": "barbell",
        "duration_weeks": 12,
        "description": "PPL with cardio finishers and isolation emphasis for an aesthetic look.",
        "routines": [
            _r("Push + Cardio", ["Incline Dumbbell Press", "Cable Crossover", "Lateral Raise", "Tricep Pushdown", "Stationary Bike"]),
            _r("Pull + Cardio", ["Lat Pulldown", "Seated Cable Row", "Face Pull", "Cable Curl", "Rowing Machine"]),
            _r("Legs + Cardio", ["Back Squat", "Romanian Deadlift", "Leg Extension", "Standing Calf Raise", "Treadmill Run"]),
        ],
    },

    # ─────────── ADVANCED ───────────
    {
        "name": "PPL 6x High Volume",
        "level": "advanced",
        "goal": "hypertrophy",
        "equipment": "barbell",
        "duration_weeks": 12,
        "description": "6 days a week, high-volume PPL. Advanced recovery required.",
        "routines": [
            _r("Push Heavy", ["Barbell Bench Press", "Overhead Press", "Incline Dumbbell Press", "Skull Crusher", "Lateral Raise"]),
            _r("Pull Heavy", ["Deadlift", "Barbell Row", "Pull Up", "Barbell Curl", "Face Pull"]),
            _r("Legs Heavy", ["Back Squat", "Romanian Deadlift", "Leg Press", "Standing Calf Raise"]),
            _r("Push Volume", ["Dumbbell Bench Press", "Cable Crossover", "Arnold Press", "Tricep Pushdown", "Rear Delt Fly"]),
            _r("Pull Volume", ["Lat Pulldown", "Seated Cable Row", "Hammer Curl", "Concentration Curl", "Face Pull"]),
            _r("Legs Volume", ["Front Squat", "Bulgarian Split Squat", "Lying Leg Curl", "Seated Calf Raise", "Hanging Leg Raise"]),
        ],
    },
    {
        "name": "5-Day Body Part Split",
        "level": "advanced",
        "goal": "hypertrophy",
        "equipment": "barbell",
        "duration_weeks": 12,
        "description": "Classic 5-day split, advanced volume per body part.",
        "routines": [
            _r("Chest", ["Barbell Bench Press", "Incline Dumbbell Press", "Dumbbell Flyes", "Cable Crossover", "Dips", "Push Up"]),
            _r("Back", ["Deadlift", "Pull Up", "Barbell Row", "T-Bar Row", "Seated Cable Row", "Face Pull"]),
            _r("Legs", ["Back Squat", "Front Squat", "Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Standing Calf Raise"]),
            _r("Shoulders", ["Overhead Press", "Arnold Press", "Lateral Raise", "Rear Delt Fly", "Front Raise", "Upright Row"]),
            _r("Arms", ["Barbell Curl", "Preacher Curl", "Hammer Curl", "Skull Crusher", "Tricep Pushdown", "Overhead Tricep Extension"]),
        ],
    },
    {
        "name": "Powerbuilding",
        "level": "advanced",
        "goal": "strength",
        "equipment": "barbell",
        "duration_weeks": 12,
        "description": "Big 3 strength with accessory hypertrophy work.",
        "routines": [
            _r("Squat Focus", ["Back Squat", "Front Squat", "Leg Press", "Lying Leg Curl", "Hanging Leg Raise"]),
            _r("Bench Focus", ["Barbell Bench Press", "Close Grip Bench Press", "Incline Dumbbell Press", "Lateral Raise", "Tricep Pushdown"]),
            _r("Deadlift Focus", ["Deadlift", "Barbell Row", "Pull Up", "Barbell Curl", "Face Pull"]),
            _r("Overhead Focus", ["Overhead Press", "Arnold Press", "Lateral Raise", "Rear Delt Fly", "Skull Crusher"]),
        ],
    },
    {
        "name": "Full Body 5x",
        "level": "advanced",
        "goal": "strength",
        "equipment": "barbell",
        "duration_weeks": 8,
        "description": "5 high-frequency full body sessions targeting strength progression.",
        "routines": [
            _r("Day 1 Heavy", ["Back Squat", "Barbell Bench Press", "Barbell Row", "Plank"]),
            _r("Day 2 Light", ["Front Squat", "Incline Dumbbell Press", "Pull Up", "Hanging Leg Raise"]),
            _r("Day 3 Medium", ["Deadlift", "Overhead Press", "Lat Pulldown", "Side Plank"]),
            _r("Day 4 Heavy", ["Back Squat", "Dumbbell Bench Press", "T-Bar Row", "Russian Twist"]),
            _r("Day 5 Power", ["Romanian Deadlift", "Close Grip Bench Press", "Pull Up", "Ab Wheel Rollout"]),
        ],
    },

    # ─────────── SPECIAL ───────────
    {
        "name": "David Laid Aesthetic Plan",
        "level": "advanced",
        "goal": "aesthetic",
        "equipment": "barbell",
        "duration_weeks": 12,
        "description": "Inspired by David Laid — 5-day aesthetic split with high volume on shoulders, back and arms.",
        "routines": [
            _r("Push (Chest Focus)", ["Barbell Bench Press", "Incline Dumbbell Press", "Cable Crossover", "Lateral Raise", "Tricep Pushdown"]),
            _r("Pull (Back Width)", ["Pull Up", "Lat Pulldown", "Seated Cable Row", "Face Pull", "Barbell Curl"]),
            _r("Legs", ["Back Squat", "Romanian Deadlift", "Leg Press", "Lying Leg Curl", "Standing Calf Raise"]),
            _r("Shoulders & Arms", ["Overhead Press", "Lateral Raise", "Rear Delt Fly", "Hammer Curl", "Overhead Tricep Extension"]),
            _r("Aesthetic Pump", ["Cable Crossover", "Face Pull", "Cable Curl", "Tricep Pushdown", "Hanging Leg Raise"]),
        ],
    },
    {
        "name": "Cut / Shred Program",
        "level": "intermediate",
        "goal": "cut",
        "equipment": "barbell",
        "duration_weeks": 8,
        "description": "Lift to retain muscle, conditioning to burn fat. 5 days, 2 cardio finishers.",
        "routines": [
            _r("Upper Push", ["Barbell Bench Press", "Overhead Press", "Lateral Raise", "Tricep Pushdown", "Mountain Climbers"]),
            _r("Upper Pull", ["Pull Up", "Barbell Row", "Face Pull", "Barbell Curl", "Burpees"]),
            _r("Lower Body", ["Back Squat", "Romanian Deadlift", "Walking Lunges", "Standing Calf Raise", "Jump Rope"]),
            _r("Full Body Conditioning", ["Goblet Squat", "Push Up", "Dumbbell Row", "Plank", "Rowing Machine"]),
            _r("Cardio + Core", ["Treadmill Run", "Hanging Leg Raise", "Russian Twist", "Plank", "Ab Wheel Rollout"]),
        ],
    },
]
